### ISSUE TITLE
How to use hide_dotted.pyw for wsl home directory?

### ISSUE THREAD

**Issue by mbkupfer** [AlbertRtk/windows_10_scripts#2]
I want to use https://github.com/AlbertRtk/windows_10_scripts/blob/main/hide_dotted.pyw from my wsl home directory. I see that the script needs to be run from a windows cmd prompt, but I can't figure out how to run a cmd scripts in my wsl home.

**Comment by mbkupfer** [comment]
The directory though is in my WSL home and not the C drive. How do I target that from the script?

**Comment by AlbertRtk** [comment]
The script has been written to work on Windows machine. It will not work on Linux.
